---

- name: SSH KeyGen command
  become: yes
  become_user: docker_root
  shell: > 
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"       
    
- name: Fetch public keyfile to local
  become: yes
  become_user: docker_root
  fetch: 
    src: "~/.ssh/id_rsa.pub"
    dest: "{{ PUBLIC_KEY_FILE }}"
    flat: yes    
    
- name: add custom key to authorized_keys
  tags: run
  authorized_key:
    user: docker_root
    state: present
    key: "{{ lookup('file','{{ USER_KEY_FILE }}')}}"
    
- name: Disable Password Authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PasswordAuthentication'
    line="PasswordAuthentication no"
    state=present
    backup=yes
           
- name: PermitRootLogin
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PermitRootLogin'
    line="PermitRootLogin yes"
    state=present
    backup=yes
    
- name: Change permissions of .ssh
  become: yes
  become_user: docker_root
  file:
    path: ~/.ssh
    owner: docker_root
    group: root
    mode: '0700' 

- name: Change permissions of authorized_keys
  become: yes
  become_user: docker_root
  file:
    path: ~/.ssh/authorized_keys
    owner: docker_root
    group: root
    mode: '0644'      

- name: Restart ssh
  shell: sleep 3; systemctl restart sshd
  async: 1
  poll: 0     
      
- name: Disable StrictHostKeyChecking
  become: yes
  become_user: docker_root
  copy:
    dest: "~/.ssh/config"
    content: |
        Host *
        StrictHostKeyChecking no            