---

- name: SSH KeyGen command
  become: yes
  become_user: docker_root
  shell: > 
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"       
    
- name: Fetch public keyfile to local
  become: yes
  become_user: docker_root
  fetch: 
    src: "~/.ssh/id_rsa.pub"
    dest: "{{ PUBLIC_KEY_FILE }}"
    flat: yes    
    
- name: add to authorized_keys
  tags: run
  authorized_key:
    user: docker_root
    state: present
    key: "{{ lookup('file','{{ USER_KEY_FILE }}')}}"
      
- name: Disable StrictHostKeyChecking
  become: yes
  become_user: docker_root
  copy:
    dest: "~/.ssh/config"
    content: |
        Host *
        StrictHostKeyChecking no            